### ISSUE TITLE
[Epic] User and Group Management

### ISSUE THREAD

**Issue by 1uka5** [UCLA-CS130-23Fall/EasySplit#1]
## Epic
People want an easier way to organize and participate in group payments. We need to create a system for people to quickly/easily manage their payment groups and preferences.

## User Stories
- [ ] Users want to be able to save their payment preferences.
- [ ] Users want to be able to create or join groups for payment.

## Use Cases and Features
- [ ] Users need to be able to create and manage user profiles with stored payment preferences and history.
- [ ] Users need to be able to formulate groups dynamically and manage multiple financial circles simultaneously with ease.
- [ ] We need to be able to ensure timely settlements and user engagement with automated, personalized notifications for bill settlements, additions, and updates.

## Tech Stack
- [ ] Frontend: Use React for a responsive site. Use the Ant Design UI framework to enhance our user interface design.
- [ ] Backend: Use AWS Dynamo DB to store an individual user's groups, preferences, and history.
