### ISSUE TITLE
[Epic] Bill Management

### ISSUE THREAD

**Issue by 1uka5** [UCLA-CS130-23Fall/EasySplit#2]
## Epic
People want more flexibility when it comes to how a group payment is made. We need to create a group payment system that gives groups flexibility and advice with how a payment is to be split and what currency each member pays in.

## User Stories
- [ ] Users want to have flexibility with how their groups split payment.
- [ ] Users want help figuring out how their groups should split payment.
- [ ] Users want to be able to choose what currency to pay in.

## Use Cases and Features
- [ ] Groups need to be able to choose how to split payments: equally, percentage-wise, or custom.
- [ ] We need to utilize LLMs to give spending suggestions to each group member.
- [ ] Users need to be able to convert between different currencies.

## Tech Stack
- [ ] Frontend: Use React for a responsive site. Use the Ant Design UI framework to enhance our user interface design.
- [ ] Backend: Use LLM in Python to provide correct payment splitting advice.
