### ISSUE TITLE
[Epic] Expense Visualization and Analysis

### ISSUE THREAD

**Issue by 1uka5** [UCLA-CS130-23Fall/EasySplit#3]
## Epic
People want to be able to easily view and analyze their spending history. We need to provide users with reports and analysis on their expenses. We also need to provide users with an easy way to export this financial data for their personal use.

## User Stories
- [ ] Users want to be able to view reports and analysis on their expenses in order to glean insights into their financial habits and trends.
- [ ] Users want to be able to export their financial data for external use or deeper personal analysis.

## Use Cases and Features
- [ ] We need to provide users with reports and analysis on their expenses.
- [ ] We need to ensure users can export their financial data seamlessly.

## Tech Stack
- [ ] Frontend: Use React for a responsive site. Use the Ant Design UI framework to enhance our user interface design.
- [ ] Backend: Use AWS Dynamo DB to store an individual user's groups and spending history.
